---
paths:
  src_paths:
    - '../sb-meta'
  json_path_rel: '../_json'
  md_path_rel: '../_markdown'
  md_web_doc_rel: '../../ga4gh-schemablocks.github.io/pages/_schemas/ga4gh'
  md_web_doc_link: '/schemas/ga4gh'
  md_web_schemas_src_rel: '../../ga4gh-schemablocks.github.io/schemas/ga4gh'
  github_repository_path: 'https://github.com/ga4gh-schemablocks/blocks/blob/master'
generator_prefix: '+generated__playground__'
jekyll_excerpt_separator: "<!--more-->"
prefix_expansions:
  orcid: 'https://orcid.org/'
links:
  sb_status_levels: "https://schemablocks.org/about/sb-status-levels.html"
