---
paths:
  src_paths:
    - '../sb-meta'
  json_path_rel: '../_json'
  md_path_rel: '../_markdown'
  md_web_path_rel: '../../ga4gh-schemablocks.github.io/pages/_schemas'
  github_repository_path: 'https://github.com/ga4gh-schemablocks/blocks/blob/master'
generator_prefix: '+generated__playground__'
